# Generated by Django 4.2.5 on 2023-09-13 09:07

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Укажите название привычки', max_length=200, verbose_name='Привычка')),
                ('completed', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habits', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
            },
        ),
        migrations.CreateModel(
            name='DailyHabit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Дата')),
                ('completed', models.BooleanField(default=False, verbose_name='Выполнено')),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_habits', to='habits.habit', verbose_name='Привычка')),
            ],
            options={
                'verbose_name': 'Ежедневная привычка',
                'verbose_name_plural': 'Ежедневные привычки',
            },
        ),
    ]
